# Generated by Django 3.1.2 on 2020-10-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201022_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='typeitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='TypeCategory',
        ),
    ]
