# Generated by Django 3.1.2 on 2020-10-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201022_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orders.typeitem'),
            preserve_default=False,
        ),
    ]
