# Generated by Django 3.1.2 on 2020-10-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201022_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
