# Generated by Django 3.1.2 on 2020-10-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201022_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(choices=[('primary', 'blue'), ('secondary', 'gray'), ('success', 'green'), ('danger', 'red'), ('warning', 'yellow'), ('info', 'ice blue'), ('light', 'light gray'), ('dark', 'dark gray'), ('white', 'white')], max_length=100),
        ),
    ]
