# Generated by Django 3.1.2 on 2020-10-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201022_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='status',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
