# Generated by Django 3.1.2 on 2020-10-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201026_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_pt',
        ),
    ]
