# Generated by Django 3.1.2 on 2020-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201027_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuschange',
            old_name='status',
            new_name='new_status',
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
